# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftPallet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftPallet
pod 'RxCocoa'

  target 'RxSwiftPalletTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftPalletUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
